### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by dankohn** [packsaddle/ruby-saddler#31]
I very much like your approach of decoupling the report runner from the underlying linters.

Would it be possible for you to share the command line to enable running Saddler on [Rails Best Practices](https://github.com/railsbp/rails_best_practices) and [Brakeman](https://github.com/presidentbeef/brakeman) as well?

Also, does Saddler support using both the text and Github reporters simultaneously?

**Comment by sanemat** [comment]
Hi @dankohn,
- Sharing the command line
- Multiple reporters
- Support Rails Best Practices
- Support Brakeman

I understand your questions, right?
- Sharing the command line

I think that sharing the command line is not a simple solution.

We can call `saddler report` multiple times.
If we want to run Saddler only once, we can create "merged checkstyle file" before calling `saddler report`.

```
merge-checkstyle (command-a ...) (command-b ...) \
| saddler report ...
```

This requires `merge-checkstyle` command, I don't know this command exists. I search "checkstyle" in rubygems, but I don't find such gem. 
- Multiple reporters

Saddler doesn't support multiple reporters yet. The alternative solution is here.

```
command-a > command-a-result.txt
cat command-a-result.txt | saddler report --reporter x
cat command-a-result.txt | saddler report --reporter y
```
- Support Rails Best Practices

`rails_best_practices` has format option, so we can set a checkstyle formatter.
I find a checkstyle formatter for rails_best_practices.

https://github.com/maroekun/rails_best_practices-formatter
- Support Brakeman

I don't find a checkstyle formatter for brakeman,
https://github.com/presidentbeef/brakeman/blob/master/OPTIONS.md#output-options

So we can use Saddler::Reporter::Github's PullRequestComment.

```
brakeman -f text \
| saddler report \
  --reporter Saddler::Reporter::Github::PullRequestComment
```

I'll add these to readme document. Thanks!

**Comment by dankohn** [comment]
Thanks for the response. Since Saddler doesn't support two simultaneous formatters, could you document using the `tee` command in bash to send the output to two different Saddler instances? See http://unix.stackexchange.com/questions/28503/how-can-i-send-stdout-to-multiple-commands

**Comment by sanemat** [comment]
@dankohn 
I added FAQ section in [readme](https://github.com/packsaddle/ruby-saddler#faq). #35 
And I split this issue to #32, #33.

Thanks for your question! Saddler needs more documents, more blog posts and more plugins. :cat: 
I believe Saddler is very useful application :muscle:
